version: "3"
services:
  spring:
    image: backend-integration-project
    build: .
    ports:
      - "8085:8085"
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=springpostgres