spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:dentist-appointments;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

server:
  port: 8085